export type ErrorKey =
  | 'EXTERNAL_ID_EXISTS'
  | 'INVENTORY_FETCH_FAILED'
  | 'NO_OFFER_FOUND'
  | 'TRADE_OFFER_FAILED'
  | 'TOO_MANY_ACTIVE_TRADES'
  | 'USER_NOT_TRADEABLE'
  | 'ITEMS_UNAVAILABLE'
  | 'ITEMS_NOT_ACCEPTED'
  | 'PRICE_CHANGED'
  | 'MERCHANT_BALANCE_LOW'
  | 'INVALID_TRADEURL'
  | 'LISTING_NOT_FOUND'
  | 'LISTING_PRICE_INVALID'
  | 'INVALID_LISTING_ID'
  | 'INSUFFICIENT_ITEM_AMOUNT'
  | 'EXCEEDS_MAX_AMOUNT'
  | 'DEPOSIT_IN_PROGRESS'
  | 'WITHDRAW_IN_PROGRESS'
  | 'TRADE_NOT_FOUND'
  | 'TRADE_CANCEL_TOO_SOON'
  | 'TRADE_NOT_CANCELLABLE'
  | 'ESCROW_NOT_ALLOWED'
  | 'INVENTORY_PRIVATE'
  | 'STEAM_UNAVAILABLE'
  | 'QUICK_BUY_UNSUPPORTED_GAME'
  | 'STEAM_RATE_LIMITED'
  | 'INSUFFICIENT_STOCK'
  | 'MIXED_SUPPLIER_TRADE'
  | 'TRADE_CANCEL_UNSUPPORTED'
  | 'ITEM_OVERSTOCKED'
  | 'VALIDATION_FAILED'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'RATE_LIMITED'
  | 'SERVER_ERROR'
  | 'SYSTEM_MAINTENANCE'
  | 'UNPROCESSABLE'
  | 'NO_BOTS_AVAILABLE'
  | 'FLEET_DEGRADED'
  | 'DEPOSITS_PAUSED'
  | 'WITHDRAWALS_PAUSED'
  | 'UNAUTHORIZED'
  | 'INVALID_TOKEN'
  | 'MISSING_BEARER'
  | 'FORBIDDEN'
  | 'MERCHANT_API_KEY_REQUIRED'
  | 'ACCOUNT_DISABLED'
  | 'USER_NOT_FOUND'
  | 'INSUFFICIENT_BALANCE'
  | 'INVALID_AMOUNT'
  | 'INSTANT_DEPOSITS_DISABLED'
  | 'CALLBACK_URL_TEST_FAILED'
  | 'MERCHANT_NO_CALLBACK_URL'
  | 'MERCHANT_CALLBACK_URL_DISABLED'
  | 'MERCHANT_NO_API_SECRET'
  | 'MISSING_API_KEY'
  | 'INVALID_API_KEY'
  | 'API_KEY_REVOKED'
  | 'API_KEY_IP_DENIED'
  | 'INSUFFICIENT_SCOPE'
  | 'NO_API_SECRET_CONFIGURED'
  | 'CLIENT_USER_NOT_FOUND'
  | 'ITEM_NOT_FOUND'
  | 'ONCHAIN_DISABLED'
  | 'ONCHAIN_CHAIN_PAUSED'
  | 'ONCHAIN_UNSUPPORTED_CHAIN'
  | 'ONCHAIN_UNSUPPORTED_TOKEN'
  | 'ONCHAIN_WITHDRAW_BELOW_MIN'
  | 'ONCHAIN_WITHDRAW_INVALID_ADDRESS'
  | 'ONCHAIN_INSUFFICIENT_HOT_BALANCE'
  | 'ONCHAIN_DEPEG'
  | 'ONCHAIN_MERCHANT_NOT_VERIFIED'
  | 'ONCHAIN_ADDRESS_CAPACITY'
  | 'ONCHAIN_CLIENT_WITHDRAW_DISABLED'
  | 'ONCHAIN_CLIENT_WITHDRAW_LIMIT'
  | 'ONCHAIN_CLIENT_WITHDRAW_BUSY'
  | 'SDK_TIMEOUT'
  | 'SDK_NETWORK'
  | 'SDK_ABORTED'
  | 'SDK_INVALID_RESPONSE'
  | (string & {});

export const AUTH_ERROR_KEYS: ReadonlySet<string> = new Set<string>([
  'UNAUTHORIZED',
  'INVALID_TOKEN',
  'MISSING_BEARER',
  'MISSING_API_KEY',
  'INVALID_API_KEY',
  'API_KEY_REVOKED',
  'API_KEY_IP_DENIED',
  'INSUFFICIENT_SCOPE',
  'FORBIDDEN',
  'MERCHANT_API_KEY_REQUIRED',
  'ACCOUNT_DISABLED',
]);

export const RATE_LIMIT_ERROR_KEYS: ReadonlySet<string> = new Set<string>(['RATE_LIMITED']);

export const VALIDATION_ERROR_KEYS: ReadonlySet<string> = new Set<string>(['VALIDATION_FAILED']);
